### ISSUE TITLE
Failed to fetch articles

### ISSUE THREAD

**Issue by a-stein** [omnivore-app/obsidian-omnivore#65]
Hi,

I recently updated the Obsidian plugin to 1.3.0. Since then I'm not able to sync any articles at all. I just receive the generic error message `Failed to fetch articles`. I already tried to reinstall the plugin and also added a new API Key, but this didn't help.

Any ideas?

**Comment by ms3056** [comment]
I am getting this problem too. A look at the inspector - this is the article title that is causing an issue:


```error
plugin:obsidian-omnivore:8190 YAMLParseError: Nested mappings are not allowed in compact mappings at line 2, column 8:

title: In Memoriam: Mac | Get Hiroshima
       ^
```

       
 I think the : and | characters are throwing it off - they are not valid YAML - there needs to be a way to clean these titles I think. In the past these characters would come in and I would clean up the title to make the YAML compliant. Now it looks like they are being blocked.

**Comment by ms3056** [comment]
Here is another title throwing the import off: How to Be a Better Manager: The Theory of the Elephant and the Rider | Inc.com

You can edit the title in Omnivore on the web to remove those characters and then bring them in just fine - but I think there should be a way to substitute these characters programmatically.

**Comment by legend053** [comment]
still not work. same issue

**Comment by trwolfe** [comment]
> still not work. same issue

Can confirm. Also getting fetch issue, even with the > implementation.

**Comment by sywhb** [comment]
Hey @legend053 @trwolfe , sorry for the mess.

May I have a look at your template settings? If possible, could you also show me a screenshot of the developer console so I could have a better understanding of the error

**Comment by trwolfe** [comment]
> Hey @legend053 @trwolfe , sorry for the mess.
> 
> May I have a look at your template settings? If possible, could you also show me a screenshot of the developer console so I could have a better understanding of the error

I only added the {{{content}}} at the end. Is that in the wrong spot?

`---
id: {{{id}}}
title: >
  {{{title}}}
{{#author}}
author: >
  {{{author}}}
{{/author}}
{{#labels.length}}
tags:
{{#labels}} - {{{name}}}
{{/labels}}
{{/labels.length}}
date_saved: {{{dateSaved}}}
{{#datePublished}}
date_published: {{{datePublished}}}
{{/datePublished}}
---

# {{{title}}}
#Omnivore

[Read on Omnivore]({{{omnivoreUrl}}})
[Read Original]({{{originalUrl}}})

{{#highlights.length}}
## Highlights

{{#highlights}}
> {{{text}}} [⤴️]({{{highlightUrl}}}) {{#labels}} #{{name}} {{/labels}}
{{#note}}

{{{note}}}
{{/note}}

{{/highlights}}
{{/highlights.length}}

{{{content}}}`

**Comment by trwolfe** [comment]
Ahhhh, so randomly, I just deleted my entire Omnivore folder from within Obsidian and re-ran the sync and it worked!

**Comment by sywhb** [comment]
> > Hey @legend053 @trwolfe , sorry for the mess.
> > May I have a look at your template settings? If possible, could you also show me a screenshot of the developer console so I could have a better understanding of the error
> 
> I only added the {{{content}}} at the end. Is that in the wrong spot?
> 
> ## `---
> id: {{{id}}}
> title: >
> {{{title}}}
> {{#author}}
> author: >
> {{{author}}}
> {{/author}}
> {{#labels.length}}
> tags:
> {{#labels}} - {{{name}}}
> {{/labels}}
> {{/labels.length}}
> date_saved: {{{dateSaved}}}
> {{#datePublished}}
> date_published: {{{datePublished}}}
> {{/datePublished}}
> # {{{title}}}
> #Omnivore
> 
> [Read on Omnivore](%7B%7B%7BomnivoreUrl%7D%7D%7D) [Read Original](%7B%7B%7BoriginalUrl%7D%7D%7D)
> 
> {{#highlights.length}}
> 
> ## Highlights
> {{#highlights}}
> 
> > {{{text}}} [⤴️](%7B%7B%7BhighlightUrl%7D%7D%7D) {{#labels}} #{{name}} {{/labels}}
> > {{#note}}
> 
> {{{note}}} {{/note}}
> 
> {{/highlights}} {{/highlights.length}}
> 
> {{{content}}} `

Hey @trwolfe , to use multiline string, we need to add two spaces before the `{{{title}}}` on the next line in the front matter.

This is invalid
```
title: >
{{{title}}}
```

And below is valid:
```
title: >
  {{{title}}}
```

**Comment by w36zl** [comment]
Heyy All, also have the fetching problem. I have tried the above strategies without success.

**Comment by trwolfe** [comment]
> I'm experiencing the same issue just today. I have already uninstalled and re-installed Omnivore but I'm still getting the same error. Also, prior to re-installing, I have completely deleted the Omnivore folder from Obsidian.

Try deleting the entire Omnivore folder and forcing a complete re-sync. Worked for me.

**Comment by w36zl** [comment]
For now as a temporary solution, I'm using obsidian46 - BRAT with the `add beta plugin with frozen version` option version: 1.2.3 and it works fine again 😃

**Comment by legend053** [comment]
> For now as a temporary solution, I'm using obsidian46 - BRAT with the `add beta plugin with frozen version` option version: 1.2.3 and it works fine again 😃

it works. version 1.2.3 works great. 👍

**Comment by mwisnefsky** [comment]
> > For now as a temporary solution, I'm using obsidian46 - BRAT with the `add beta plugin with frozen version` option version: 1.2.3 and it works fine again 😃
> 
> it works. version 1.2.3 works great. 👍

Confirmed this worked for me as well

**Comment by ms3056** [comment]
For me deleting all of the imports in Obsidian and changing the config with this worked fine. 

```yaml
title: >
  {{{title}}}
```

**Comment by sywhb** [comment]
Hey guys, sorry for the delay. I have fixed this error in the latest release `1.3.1`.

It includes:
## Bug Fixes

* Fixed `Failed to fetch articles` error due to invalid YAML format in the front matter. Now you can define which variables to be used in the front matter

## Feature
* Added a reset template button to reset the template to default

![](https://cdn.discordapp.com/attachments/855181471643861002/1110401373855547443/Screenshot_2023-05-23_at_10.58.03_AM.png)

![](https://cdn.discordapp.com/attachments/855181471643861002/1110401374111408208/Screenshot_2023-05-23_at_10.58.19_AM.png)

Please let me know if it works for you guys and looking forward to your feedback

**Comment by ms3056** [comment]
I don't like how the tags are coming in. It messes up all of my Dataview Queries. 

I don't like:

tags:
    - name: tag1

I want 

tags: [tag1, tag2, tag3]

Or some other YAML-compliant multiple entry methods.

**Comment by ms3056** [comment]
this would work - just remove "name:" for tags please:

tags:
     - tag1
     - tag2
     - tag3

**Comment by sywhb** [comment]
> this would work - just remove "name:" for tags please:
> 
> tags: - tag1 - tag2 - tag3

Sorry for the breaking change. I'm working on a fix now

**Comment by ms3056** [comment]
no worries. i appreciate the ability to bring Omnivore into Obsidian. Thank you for your hard work.

**Comment by sywhb** [comment]
Hey @ms3056 , a new version `1.3.2` is released to use below format for the `tags` in the front matter.
```
tags:
  - tag1
  - tag2
  - tag3
```

Could you upgrade your plugin and try again?

**Comment by ms3056** [comment]
This has worked for me - thanks!

**Comment by marcgilgien** [comment]
> Hey guys, sorry for the delay. I have fixed this error in the latest release `1.3.1`.
> 
> It includes:
> 
> ## Bug Fixes
> * Fixed `Failed to fetch articles` error due to invalid YAML format in the front matter. Now you can define which variables to be used in the front matter
> 
> ## Feature
> * Added a reset template button to reset the template to default
> 
> ![](https://camo.githubusercontent.com/6671d2278f93cbf39904ee5b9b31ff2b9f264a5038f73abed3b288fff2c45add/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3835353138313437313634333836313030322f313131303430313337333835353534373434332f53637265656e73686f745f323032332d30352d32335f61745f31302e35382e30335f414d2e706e67)
> 
> ![](https://camo.githubusercontent.com/4a12654279538cc2065c90a3e705f3381be90507607ca302dbad0da6c136a285/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3835353138313437313634333836313030322f313131303430313337343131313430383230382f53637265656e73686f745f323032332d30352d32335f61745f31302e35382e31395f414d2e706e67)
> 
> Please let me know if it works for you guys and looking forward to your feedback

This does work. But unfortunatly it prevents you from setting your own keys in fronmatter, like:
---
created: {{{dateSaved}}}
---
As I use my own keys this is now unusable to me (Unless I did miss the correct way to do this).

**Comment by ShaddyDC** [comment]
Can you update the template under [this link](https://docs.omnivore.app/integrations/obsidian.html#controlling-the-layout-of-the-data-imported-to-obsidian) to include the multiline frontmatter fields?

Unfortunately, it still does not seem to be working for me on 1.3.3 after resetting the template to default.
I'm not getting an error, it just seems to be stuck syncing for ever.
![image](https://github.com/omnivore-app/obsidian-omnivore/assets/18403034/95f9af5c-d960-429c-b1ee-c21437a1e119)

I got some 5xx error with the generic error message `Failed to fetch articles` of the OP once, but that was over the course of hours, and I forgot making a screenshot or noting the stacktrace.
Switching to version 1.2.3 fixed the issue for me as well.

<details>
  <summary>Template</summary>
  
 
  ```
# {{{title}}}
#Omnivore

[Read on Omnivore]({{{omnivoreUrl}}})
[Read Original]({{{originalUrl}}})

{{#highlights.length}}
## Highlights

{{#highlights}}
> {{{text}}} [⤴️]({{{highlightUrl}}}) {{#labels}} #{{name}} {{/labels}}
{{#note}}

{{{note}}}
{{/note}}

{{/highlights}}
{{/highlights.length}}
  ```
  
</details>

**Comment by legend053** [comment]
version 1.3.3 does not work again on fetching whole articles. It worked before, but failed to fetch articles starting today.

**Comment by legend053** [comment]
> version 1.3.3 does not work again on fetching whole articles. It worked before, but failed to fetch articles starting today.

I restore it back to 1.2.3. Everything works perfect.

**Comment by Spatial-Warrior** [comment]
Version 1.3.3 getting "Failed to fetch articles". I reinstalled plugin on Obsidian and generated a new API key but same result. Interestingly it brought across 3 files from archive folder but then same result on refresh. I'd be very grateful if you could find a fix.

**Comment by ms3056** [comment]
> Version 1.3.3 getting "Failed to fetch articles". I reinstalled plugin on Obsidian and generated a new API key but same result. Interestingly it brought across 3 files from archive folder but then same result on refresh. I'd be very grateful if you could find a fix. 

Make sure even when you reinstall that you remove the value of Last Sync in the Omnivore plug-in settings. This tells the plug-in to not bring anything over that is older than that date.

**Comment by sywhb** [comment]
Hey guys, **Omnivore plugin 1.4.0** is out.

I hope it will solve all the issues with parsing YAML in the front matter and the sync will continue even if there was a parsing error.

Additionally, now you can create an alias for the metadata in the front matter in the format of `metadata::alias`. For example, `state::status` will create a metadata `status` to represent the `state`. The available metadata could be found [here](https://docs.omnivore.app/integrations/obsidian.html#front-matter).

Screenshot:
<img width="680" alt="Screenshot 2023-05-31 at 4 56 05 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/494919c3-2386-4d88-be70-d20129acf1cf">

Moreover, for users with the need to put hardcoded metadata in the front matter or some other advanced usage, we have added a "front matter template" section under the advanced settings. It will be override the "Front matter" if set. Sample template could be found [here](https://docs.omnivore.app/integrations/obsidian.html#front-matter-template).

Screenshot:
<img width="681" alt="Screenshot 2023-05-31 at 4 56 17 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/5889176a-611d-481e-bc17-43e8aec9e4f5">

**Comment by w36zl** [comment]
Heyy All, great update!! such amazing developments!! works well on my iphone, but for some reason not on my windows machine

the thing i have done:

- front matter template
- API key
- last sync
- have put all the same settings as my iPhone
- uninstall 
- reinstall

Looking forward to an answer

**Comment by w36zl** [comment]
Hi All, for some reason I do not understand (on my windows machine) it still notifies `failed to fetch articles` 
On my iPhone and iPad the obsidian plugin just works fine.

what I tried till now:

- copied the obsidian vault folder of my iphone to my windows machine (with as result: it works shortly and then stops functioning)
- use the exact same frontmatter template as my iphone obsidian vault
- tried the standard template from the website
- deleted the `last sync`
- uninstalled and reinstalled

hope that anyone has some idea that can help

**Comment by legend053** [comment]
> Hi All, for some reason I do not understand (on my windows machine) it still notifies `failed to fetch articles` On my iPhone and iPad the obsidian plugin just works fine.
> 
> what I tried till now:
> 
> * copied the obsidian vault folder of my iphone to my windows machine (with as result: it works shortly and then stops functioning)
> * use the exact same frontmatter template as my iphone obsidian vault
> * tried the standard template from the website
> * deleted the `last sync`
> * uninstalled and reinstalled
> 
> hope that anyone has some idea that can help

Same here. 1.4.0 has this issue too. So far,1.2.3 works best without such issue. So, roll back to version 1.2.3.

**Comment by jacksonh** [comment]
I need to verify this on Windows, but I believe the issue I've seen is emoji's in titles causing invalid Window's file names.

**Comment by sywhb** [comment]
Hey @w36zl @legend053 , thanks for reporting.

After some research, we found out that it's the control characters in the filename caused the error on Windows and it has be fixed in the latest version `1.4.1`.

Could you please upgrade your plugin and let me know if it works for you?

Thank you!

**Comment by w36zl** [comment]
That's great! Thank you will check when I returned home 🤩

**Comment by w36zl** [comment]
Yeeeeey 😍😍😍 it's working! Such a joy!! Thank you

**Comment by SAK59823** [comment]
I'm experiencing an issue when trying to fetch files with Japanese characters in their filenames using the Omnivore plugin in Obsidian.

The error I encounter is:

Error: EINVAL: invalid argument, open 'H:\Omnivore\2023-06-20\ - Wikipedia.md'

It seems that the Japanese characters are not being included in the filenames.

Example of original file name
 "'( Japanese characters ) - Wikipedia.md'

The Filename setting in the Omnivore plugin, which I've configured to use {{{title}}} for the file name, appears to be causing this issue. When I adjust this setting to {{{dateSaved}}}, the file fetch is successful, even for webpages with a Japanese title

This problem doesn't occur when the same Wikipedia article is in English.

**Comment by sywhb** [comment]
@SAK59823 sorry, there is a bug with the current version and I'm fixing it now. Should be done pretty soon

**Comment by LightTemplar** [comment]
@sywhb, is it possible to latinize titles for filenames? not for all, but optional, of course.

**Comment by sywhb** [comment]
Hey @SAK59823 , I just released `1.5.1` to fix this bug ;)

<img width="223" alt="Screenshot 2023-06-21 at 10 13 03 AM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/a7804788-5fab-4ec5-9cd9-e4398a9e4b10">

**Comment by sywhb** [comment]
> @sywhb, is it possible to latinize titles for filenames? not for all, but optional, of course.

Hey @LightTemplar , currently we do not latinize titles for filenames but I will take at some libraries that we can use

**Comment by SAK59823** [comment]
> Hey @SAK59823 , I just released `1.5.1` to fix this bug ;)
> 
> <img alt="Screenshot 2023-06-21 at 10 13 03 AM" width="223" src="https://user-images.githubusercontent.com/12963965/247376882-a7804788-5fab-4ec5-9cd9-e4398a9e4b10.png">

Thank you!!

**Comment by wieniawski-lai** [comment]
I still face this problem, and my version is 1.5.3.
The only information is:
```
Failed to fetch articles
```
And I have set
1. API key
2. template as methioned in above discussion.
3. local save folder
![image](https://github.com/omnivore-app/obsidian-omnivore/assets/70927596/93895198-41e1-462a-b8bd-11c06265a4ba)

**Comment by sywhb** [comment]
Hey @wieniawski-lai , would you mind sharing with me your username so I can check in the backend?

**Comment by wieniawski-lai** [comment]
> Hey @wieniawski-lai , would you mind sharing with me your username so I can check in the backend?

My username is wieniawski in omnivore.

**Comment by sywhb** [comment]
@wieniawski-lai Thank you! I have found the API call made by the plugin is successful and results have been returned so I guess the error comes from the plugin itself.

Would you mind sharing with me the article template config in your plugin settings?

<img width="670" alt="Screenshot 2023-07-21 at 6 39 52 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/00b26be8-5ec5-49d4-b5ae-09e924b2b1ed">

**Comment by wieniawski-lai** [comment]
> @wieniawski-lai Thank you! I have found the API call made by the plugin is successful and results have been returned so I guess the error comes from the plugin itself.
> 
> Would you mind sharing with me the article template config in your plugin settings?
> 
> <img alt="Screenshot 2023-07-21 at 6 39 52 PM" width="670" src="https://user-images.githubusercontent.com/12963965/255151404-00b26be8-5ec5-49d4-b5ae-09e924b2b1ed.png">

sure, pls see below
```
# {{{title}}}
#Omnivore

[Read on Omnivore]({{{omnivoreUrl}}})
[Read Original]({{{originalUrl}}})

{{#highlights.length}}
## Highlights

{{#highlights}}
> {{{text}}} [⤴️]({{{highlightUrl}}}) {{#labels}} #{{name}} {{/labels}} ^{{{highlightID}}}
{{#note}}

{{{note}}}
{{/note}}

{{/highlights}}
{{/highlights.length}}
```

**Comment by sywhb** [comment]
Hey @wieniawski-lai , sorry for the late reply. I have released `1.6.0` to address a few fetching issues.

Could you please kindly upgrade your plugin and re-sync all the articles?

We need to clear this "Last Sync" config in the plugin settings and then click on the sync icon again.
 
<img width="671" alt="Screenshot 2023-08-03 at 6 24 08 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/3aec3824-424b-4fde-8edc-b7addd0c3c82">

**Comment by wieniawski-lai** [comment]
thx, @sywhb 
I have updated to v1.6.0, and clear "Last Sync" as you said.
Besides, on windows, my folder to save synced data is
`E:/backup/note/0.MISC/5.Omnivore/{{{date}}}`
![image](https://github.com/omnivore-app/obsidian-omnivore/assets/70927596/b1ecdb33-1d47-489c-9d68-ba9e2405a510)

And at this time, there is not error happens. However, I still can not find any md file under `E:/backup/note/0.MISC/5.Omnivore/{{{date}}}`

Is there any log that I can see?

**Comment by sywhb** [comment]
Thanks for the reply @wieniawski-lai .

I think the "Folder" and "Attachment Folder" should be relative path in the Vault.
<img width="693" alt="Screenshot 2023-08-04 at 1 00 08 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/235ff70b-e207-481e-a888-2ad1f91a85fc">

We do not support saving notes to a different vault for now

**Comment by wieniawski-lai** [comment]
thx, @sywhb 
I have changed it into relative path in the Vault.
but some thing happens.
![image](https://github.com/omnivore-app/obsidian-omnivore/assets/70927596/b7799615-0161-40e1-a892-5db7731a3386)
above message reported, but nothing is downloaded in to the folder I set.

**Comment by sywhb** [comment]
@wieniawski-lai , did you also clear the `lastSync` timestamp before syncing? Or you could try to use command palette (Control + P), search for resync and click on the "Omnivore: Resync all articles" 

<img width="717" alt="Screenshot 2023-08-04 at 4 24 37 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/9af928ee-9847-4d36-947b-8a5b571a8cc9">

**Comment by echoleaf** [comment]
I ran into this error just now and resolved it by closing & reopening Obsidian. I had made a lot of organizational changes with folder names, moving folders, etc. The plugin had the correct new folder for import but it didn't work until after restart.

**Comment by wieniawski-lai** [comment]
> @wieniawski-lai , did you also clear the `lastSync` timestamp before syncing? Or you could try to use command palette (Control + P), search for resync and click on the "Omnivore: Resync all articles" in Obsidian.
> 
> <img alt="Screenshot 2023-08-04 at 4 24 37 PM" width="717" src="https://user-images.githubusercontent.com/12963965/258365299-9af928ee-9847-4d36-947b-8a5b571a8cc9.png">

I also did you what you said to clear the `lastSync` before syncing. However, there is still nothing downloaded.
My question is that is there any log that I can see to debug the whole processing?

**Comment by sywhb** [comment]
@wieniawski-lai , that is so weird.

To view the logs, you could Toggle the Developer Tools
<img width="238" alt="Screenshot 2023-08-14 at 12 03 38 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/2d26e6d7-0994-46df-9f40-09143e1c7694">

**Comment by wieniawski-lai** [comment]
> @wieniawski-lai , that is so weird.
> 
> To view the logs, you could Toggle the Developer Tools <img alt="Screenshot 2023-08-14 at 12 03 38 PM" width="238" src="https://user-images.githubusercontent.com/12963965/260355380-2d26e6d7-0994-46df-9f40-09143e1c7694.png">

hmm,

I didnot see menu bar in my obsidian as yours:
![image](https://github.com/omnivore-app/obsidian-omnivore/assets/70927596/f3f183ae-76bb-47be-89ed-2428777956e7)

Does it because of obsidian theme?

**Comment by sywhb** [comment]
@wieniawski-lai , probably it's because I'm using MacOS.

If you would like to access developer tools, you can find it in the menu bar (View > Toggle Developer Tools) or use the hotkey (cmd+ option + i on Mac and ctrl + shift + i for Windows).

**Comment by danicotillas** [comment]
> > > Hey @legend053 @trwolfe , sorry for the mess.
> > > May I have a look at your template settings? If possible, could you also show me a screenshot of the developer console so I could have a better understanding of the error
> > 
> > 
> > I only added the {{{content}}} at the end. Is that in the wrong spot?
> > ## `---
> > id: {{{id}}}
> > title: >
> > {{{title}}}
> > {{#author}}
> > author: >
> > {{{author}}}
> > {{/author}}
> > {{#labels.length}}
> > tags:
> > {{#labels}} - {{{name}}}
> > {{/labels}}
> > {{/labels.length}}
> > date_saved: {{{dateSaved}}}
> > {{#datePublished}}
> > date_published: {{{datePublished}}}
> > {{/datePublished}}
> > # {{{title}}}
> > #Omnivore
> > [Read on Omnivore](%7B%7B%7BomnivoreUrl%7D%7D%7D) [Read Original](%7B%7B%7BoriginalUrl%7D%7D%7D)
> > {{#highlights.length}}
> > ## Highlights
> > {{#highlights}}
> > > {{{text}}} [⤴️](%7B%7B%7BhighlightUrl%7D%7D%7D) {{#labels}} #{{name}} {{/labels}}
> > > {{#note}}
> > 
> > 
> > {{{note}}} {{/note}}
> > {{/highlights}} {{/highlights.length}}
> > {{{content}}} `
> 
> Hey @trwolfe , to use multiline string, we need to add two spaces before the `{{{title}}}` on the next line in the front matter.
> 
> This is invalid
> 
> ```
> title: >
> {{{title}}}
> ```
> 
> And below is valid:
> 
> ```
> title: >
>   {{{title}}}
> ```

Hi! I'm sorry but I don't know where I have to write down that so my file is named after the title without special characters. 
I have the "Front Matter" field where I set the alias, date_saved, etc... and then the "Article template" where all the information goes on the file.

Thanks for the help!
