### ISSUE TITLE
The title in simplified Chinese appears as garbled code when synced to Obsidian

### ISSUE THREAD

**Issue by Adam-Teng** [omnivore-app/obsidian-omnivore#7]
Like this:
![image](https://user-images.githubusercontent.com/71575606/212449915-b22dc409-3c3d-4728-a6b3-4ae7e12acbe5.png)
The title field in the image is the title of the article I want, but the article title synchronized by the plug-in is a mess of codes.

**Comment by sywhb** [comment]
Thanks for reporting! I'm working on a fix here: https://github.com/omnivore-app/obsidian-omnivore/pull/8

**Comment by jacksonh** [comment]
I think technically this is fixed now, right?

**Comment by sywhb** [comment]
Yeah, it should but there is something wrong with the semantic-release, of course.

Trying to understand why

**Comment by sywhb** [comment]
It doesn't use the correct version number. I will manually release one first while I'm figuring it out

**Comment by sywhb** [comment]
`1.0.1` is released which should fix this issue @jacksonh @Adam-Teng

**Comment by sywhb** [comment]
Oh, because our PR is still pending on the Obsidian side so we have to manually update the plugin by replacing the files under the plugin folder with the files in the release assets

**Comment by StrollStars** [comment]
@sywhb @jacksonh Does the string of numbers and letters after the dash mean something? It will only appear in the filename, is it possible to cancel?
PS:There is no problem with Chinese characters, but Chinese punctuation is still a problem.

**Comment by sywhb** [comment]
Hey @StrollStars, it is part of the slug of the article which is used to differentiate the files with the same filename in case we overwrite them. For example, tweets saved in Omnivore share the same title.

We could probably keep symbols like punctuation marks in the filename but I'm not sure if that will cause us some trouble. I will take a look at the symbols allowed in the filename

**Comment by StrollStars** [comment]
> it is part of the slug of the article which is used to differentiate the files with the same filename in case we overwrite them.

Can it be replaced by adding a serial number before the title, so that it can be distinguished. It would be better if it can support custom file names, just like [11](https://github.com/omnivore-app/obsidian-omnivore/issues/12).

**Comment by StrollStars** [comment]
@sywhb Can the ID which is used to differentiate the files with the same filename be placed in the metadata area? This makes renaming easier.

**Comment by sywhb** [comment]
> @sywhb Can the ID which is used to differentiate the files with the same filename be placed in the metadata area? This makes renaming easier.

Hey @StrollStars, sorry for the late reply. Yes, that's a good idea and I can place the ID at the metadata area.

> Can it be replaced by adding a serial number before the title, so that it can be distinguished. It would be better if it can support custom file names, just like https://github.com/omnivore-app/obsidian-omnivore/issues/12.

Yes, I will try adding a serial number before/after the title and I guess we need to remove/replace the illegal characters in the the filename too

**Comment by StrollStars** [comment]
> Yes, I will try adding a serial number before/after the title and I guess we need to remove/replace the illegal characters in the the filename too
Thank you for your reply. I think it is necessary.

BTW, my `date_saved` is always null.
And is it possible to add the article `publish_date`?

**Comment by sywhb** [comment]
> BTW, my date_saved is always null.
It probably is related to the `dateFormat` config. I will take a look.

> And is it possible to add the article publish_date?
Yeah, I will add this one too.

**Comment by sywhb** [comment]
#20

**Comment by sywhb** [comment]
Hey @StrollStars, version `1.0.5` is released to address these few issues:
1. used `title` as the filename and `id` to deduplicate
2. fixed `date_saved` to be `null` in the frontmatter
3. added `date_published` to the frontmatter
4. `date_format` and `folder_format` can be config in the settings

**Comment by StrollStars** [comment]
@sywhb Thank you very much, it's great.
